### ISSUE TITLE
Support non-UTF8 encodings

### ISSUE THREAD

**Issue by GreatHX** [yishn/Sabaki#121]
Thanks for doing such a cool Go software! 
But when I am trying to open SGF files with Chinese comments in them, the text doesn't display very well(Mac Version). 

<img width="789" alt="2016-08-24 13 40 49" src="https://cloud.githubusercontent.com/assets/21212927/17919469/67b4cee0-6a00-11e6-8093-a8f6460014c2.png">

**Comment by yishn** [comment]
Thanks! I'm currently on vacation, but I'll investigate when I come back.

**Comment by apetresc** [comment]
@GreatHX It's likely an encoding issue – I tried with some UTF-8 encoded Chinese characters and it worked great. Can you perhaps attach the SGF you're trying to open to this ticket? (You can do that just by dragging-and-dropping it onto the comment box). That will help diagnose the problem.

**Comment by GreatHX** [comment]
@yishn @apetresc Thanks！This is the SGF with the problem.

[围棋定式一月通.sgf.zip](https://github.com/yishn/Sabaki/files/435859/sgf.zip)

**Comment by apetresc** [comment]
Yes, indeed, the problem is that this file is encoded with GB18030 which is not being detected properly. Converting it to UTF-8 with, say:

```
iconv -f GB18030 -t UTF-8 chinese.sgf > chinese_utf8.sgf
```
results in a readable file (attached):
![screenshot 2016-08-24 21 07 03](https://cloud.githubusercontent.com/assets/14872/17953126/b78ab43c-6a3e-11e6-88c2-594c7d21eefa.png)

Given that the encoding was properly set in the SGF (through the `CA` property) it should be possible to detect and apply this. I'll take a look and see if it's easy enough for me to do it :)
[chinese_utf8.sgf.zip](https://github.com/yishn/Sabaki/files/435960/chinese_utf8.sgf.zip)

**Comment by GreatHX** [comment]
@apetresc Thanks a lot for your answer!

**Comment by apetresc** [comment]
@GreatHX I've implemented a fix in my branch [apetresc/sabaki@encoding](https://github.com/apetresc/sabaki/tree/encoding) which works for your file. There's still a bit more work to be done, though, and I'd love to get @yishn's thoughts on it before I fix the last few bits.

**Comment by GreatHX** [comment]
@apetresc I really appreciate your fixing!

**Comment by solatale** [comment]
@apetresc I've tried your encoding version. Thank you for your fixing! Actually, some Chinese SGFs work well, but some are still not. I appreciate the solution of converting GB encoding to UTF-8, for it is very convenient to me.

BTW, I attach my failed SGF file here.
[16881212.sgf.zip](https://github.com/yishn/Sabaki/files/465256/16881212.sgf.zip)

**Comment by yishn** [comment]
@solatale Your attached SGF file doesn't specify the encoding via `CA` property, so Sabaki doesn't know which encoding to use. You can fix your SGF file by inserting `CA[GB2312]` as the second line. I don't think Sabaki can do anything about that.

**Comment by solatale** [comment]
@yishn Yeah, thank you very much for your enlightening! I got it. Sabaki is an outstanding Go program under all OSs. I like it as boys like the Transformers:)
